#!/bin/bash

git clone https://github.com/ProjectInfinity-X/manifest.git manifest
git clone https://github.com/ProjectInfinity-X/packages_modules_adb.git packages/modules/adb
git clone https://github.com/ProjectInfinity-X/packages_modules_Bluetooth.git packages/modules/Bluetooth
git clone https://github.com/ProjectInfinity-X/packages_modules_common.git packages/modules/common
git clone https://github.com/ProjectInfinity-X/packages_modules_Connectivity.git packages/modules/Connectivity
git clone https://github.com/ProjectInfinity-X/packages_modules_Permission.git packages/modules/Permission
git clone https://github.com/ProjectInfinity-X/packages_modules_Wifi.git packages/modules/Wifi
git clone https://github.com/ProjectInfinity-X/packages_apps_BtHelper.git packages/apps/BtHelper
git clone https://codeberg.org/LFS-dump/packages_apps_Settings.git packages/apps/Settings
git clone https://github.com/ProjectInfinity-X/packages_services_DeviceAsWebcam.git packages/services/DeviceAsWebcam
git clone https://github.com/ProjectInfinity-X/packages_services_Telecomm.git packages/services/Telecomm
git clone https://github.com/ProjectInfinity-X/packages_services_Telephony.git packages/services/Telephony
git clone https://github.com/ProjectInfinity-X/bootable_deprecated-ota.git bootable/deprecated-ota
git clone https://github.com/ProjectInfinity-X/bootable_recovery.git bootable/recovery
git clone https://github.com/ProjectInfinity-X/build_bazel.git build/bazel
git clone https://github.com/ProjectInfinity-X/build.git build/make
git clone https://github.com/ProjectInfinity-X/build_soong.git build/soong
git clone https://github.com/ProjectInfinity-X/device_qcom_sepolicy_vndr.git device/qcom/sepolicy_vndr/legacy-um
cd device/qcom/sepolicy_vndr/legacy-um && git checkout 16 && cd -
git clone https://github.com/ProjectInfinity-X/device_infinity_sepolicy.git device/lineage/sepolicy
git clone https://github.com/ProjectInfinity-X/external_arm-optimized-routines.git external/arm-optimized-routines
git clone https://github.com/ProjectInfinity-X/external_avb.git external/avb
git clone https://github.com/ProjectInfinity-X/external_bouncycastle.git external/bouncycastle
git clone https://github.com/ProjectInfinity-X/external_cronet.git external/cronet
git clone https://github.com/ProjectInfinity-X/external_dtc.git external/dtc
git clone https://github.com/ProjectInfinity-X/external_e2fsprogs.git external/e2fsprogs
git clone https://github.com/ProjectInfinity-X/external_gptfdisk.git external/gptfdisk
git clone https://github.com/ProjectInfinity-X/external_jemalloc_new.git external/jemalloc_new
git clone https://github.com/ProjectInfinity-X/external_lz4.git external/lz4
git clone https://github.com/ProjectInfinity-X/external_mksh.git external/mksh
git clone https://github.com/ProjectInfinity-X/external_piex.git external/piex
git clone https://github.com/ProjectInfinity-X/external_setupcompat.git external/setupcompat
git clone https://github.com/ProjectInfinity-X/external_tinycompress.git external/tinycompress
git clone https://github.com/ProjectInfinity-X/frameworks_av.git frameworks/av
git clone https://codeberg.org/LFS-dump/frameworks_base.git frameworks/base
git clone https://github.com/ProjectInfinity-X/frameworks_libs_systemui.git frameworks/libs/systemui
git clone https://github.com/ProjectInfinity-X/frameworks_native.git frameworks/native
git clone https://github.com/ProjectInfinity-X/frameworks_opt_calendar.git frameworks/opt/calendar
git clone https://github.com/ProjectInfinity-X/frameworks_opt_colorpicker.git frameworks/opt/colorpicker
git clone https://github.com/ProjectInfinity-X/frameworks_opt_net_wifi.git frameworks/opt/net/wifi
git clone https://github.com/ProjectInfinity-X/frameworks_opt_telephony.git frameworks/opt/telephony
git clone https://github.com/ProjectInfinity-X/hardware_broadcom_libbt.git hardware/broadcom/libbt
git clone https://github.com/ProjectInfinity-X/hardware_interfaces.git hardware/interfaces
git clone https://github.com/ProjectInfinity-X/hardware_libhardware.git hardware/libhardware
git clone https://github.com/ProjectInfinity-X/hardware_lineage_compat.git hardware/lineage/compat
git clone https://github.com/ProjectInfinity-X/hardware_lineage_interfaces.git hardware/lineage/interfaces
git clone https://github.com/ProjectInfinity-X/hardware_qcom_wlan.git hardware/qcom/wlan
git clone https://github.com/ProjectInfinity-X/hardware_samsung_nfc.git hardware/samsung/nfc
git clone https://github.com/ProjectInfinity-X/hardware_st_nfc.git hardware/st/nfc
git clone https://github.com/ProjectInfinity-X/kernel_configs.git kernel/configs
git clone https://github.com/ProjectInfinity-X/custom-sdk.git lineage-sdk
git clone https://github.com/ProjectInfinity-X/art.git art
git clone https://github.com/ProjectInfinity-X/bionic.git bionic
git clone https://github.com/ProjectInfinity-X/packages_apps_Dialer.git packages/apps/Dialer
git clone https://github.com/ProjectInfinity-X/packages_apps_DocumentsUI.git packages/apps/DocumentsUI
git clone https://github.com/ProjectInfinity-X/packages_apps_Messaging.git packages/apps/Messaging
git clone https://github.com/ProjectInfinity-X/packages_apps_ColumbusService.git packages/apps/ColumbusService
git clone https://github.com/ProjectInfinity-X/packages_apps_FaceUnlock.git packages/apps/FaceUnlock
git clone https://github.com/ProjectInfinity-X/packages_apps_GameSpace.git packages/apps/GameSpace
git clone https://codeberg.org/LFS-dump/packages_apps_InfinitySuite.git packages/apps/InfinitySuite
git clone https://github.com/ProjectInfinity-X/packages_apps_LMOFreeform.git packages/apps/LMOFreeform
git clone https://github.com/ProjectInfinity-X/packages_apps_Parts.git packages/apps/LineageParts
git clone https://github.com/ProjectInfinity-X/packages_apps_SettingsIntelligence.git packages/apps/SettingsIntelligence
git clone https://github.com/ProjectInfinity-X/packages_apps_ThemePicker.git packages/apps/ThemePicker
git clone https://github.com/ProjectInfinity-X/packages_apps_Updater.git packages/apps/Updater
git clone https://github.com/ProjectInfinity-X/packages_apps_WallpaperPicker2.git packages/apps/WallpaperPicker2
git clone https://github.com/ProjectInfinity-X/packages_overlays_Themes.git packages/overlays/Themes
git clone https://github.com/ProjectInfinity-X/prebuilts_infinity-sdk.git prebuilts/infinity-sdk
git clone https://github.com/ProjectInfinity-X/platform_testing.git platform_testing
git clone https://github.com/ProjectInfinity-X/system_bpf.git system/bpf
git clone https://github.com/ProjectInfinity-X/system_chre.git system/chre
git clone https://github.com/ProjectInfinity-X/system_core.git system/core
git clone https://github.com/ProjectInfinity-X/system_extras.git system/extras
git clone https://github.com/ProjectInfinity-X/system_libhidl.git system/libhidl
git clone https://github.com/ProjectInfinity-X/system_libhwbinder.git system/libhwbinder
git clone https://github.com/ProjectInfinity-X/system_logging.git system/logging
git clone https://github.com/ProjectInfinity-X/system_media.git system/media
git clone https://github.com/ProjectInfinity-X/system_memory_lmkd.git system/memory/lmkd
git clone https://github.com/ProjectInfinity-X/system_netd.git system/netd
git clone https://github.com/ProjectInfinity-X/system_security.git system/security
git clone https://github.com/ProjectInfinity-X/system_sepolicy.git system/sepolicy
git clone https://github.com/ProjectInfinity-X/system_tools_mkbootimg.git system/tools/mkbootimg
git clone https://github.com/ProjectInfinity-X/system_update_engine.git system/update_engine
git clone https://github.com/ProjectInfinity-X/system_vold.git system/vold
git clone https://github.com/ProjectInfinity-X/vendor_extras.git vendor/extras
git clone https://github.com/ProjectInfinity-X/vendor_support.git vendor/support
git clone https://codeberg.org/LFS-dump/vendor_google_gms.git vendor/gms
git clone https://github.com/ProjectInfinity-X/vendor_infinity.git vendor/infinity
git clone https://github.com/ProjectInfinity-X/vendor_gms_overlays.git vendor/pixel-style